import type { Metadata } from "next";
import { Playfair_Display } from "next/font/google";
import "../globals.css";
import Topbar from "@/components/shared/Topbar";
import { AuthProvider } from "../providers/AuthProvider";


const playFair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
   weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Hustle Connect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playFair.variable} antialiased`}
      >
        <AuthProvider>
          <Topbar />
          <main className="flex flex-col items-center justify-center gradient-bg">
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
